"""Unit and integration tests for FHIR R4 and Jeevandata Clinical Intake Adapter."""

from __future__ import annotations

import json
import sqlite3

import pytest
from src.wellcare.database import Database
from src.wellcare.utils.fhir_adapter import FHIRAdapter, IngestionResult


@pytest.fixture
def test_db(tmp_path):
    """Fixture providing an isolated SQLite database instance."""
    db_file = tmp_path / "test_wellcare.db"

    class TempDatabase(Database):
        def __init__(self):
            super().__init__()
            self.conn = sqlite3.connect(str(db_file), check_same_thread=False)
            self.conn.execute("PRAGMA foreign_keys = ON")
            self.cur = self.conn.cursor()
            self._create_table()

    db = TempDatabase()
    yield db
    db.close()


@pytest.fixture
def sample_fhir_bundle() -> dict:
    """Fixture returning a realistic FHIR R4 Bundle generated by Jeevandata."""
    return {
        "resourceType": "Bundle",
        "id": "bundle-session-12345",
        "type": "transaction",
        "entry": [
            {
                "resource": {
                    "resourceType": "Patient",
                    "id": "pat-99",
                    "identifier": [
                        {"system": "https://jeevandata.care/patients", "value": "pat-99"}
                    ],
                    "name": [
                        {
                            "use": "official",
                            "family": "Sharma",
                            "given": ["Rahul"],
                        }
                    ],
                    "birthDate": "1994-06-15",
                    "gender": "male",
                    "telecom": [{"system": "phone", "value": "9876543210", "use": "mobile"}],
                    "address": [{"text": "42 MG Road, Bangalore", "postalCode": "560001"}],
                },
                "request": {"method": "PUT", "url": "Patient/pat-99"},
            },
            {
                "resource": {
                    "resourceType": "Encounter",
                    "id": "enc-12345",
                    "status": "finished",
                    "reasonCode": [
                        {
                            "coding": [{"code": "18484000", "display": "Fever"}],
                            "text": "Acute fever and dry cough for 3 days",
                        }
                    ],
                },
                "request": {"method": "PUT", "url": "Encounter/enc-12345"},
            },
            {
                "resource": {
                    "resourceType": "Observation",
                    "id": "obs-1",
                    "status": "final",
                    "code": {"text": "Body Temperature"},
                    "valueString": "102 F, high grade",
                },
                "request": {"method": "PUT", "url": "Observation/obs-1"},
            },
            {
                "resource": {
                    "resourceType": "Observation",
                    "id": "obs-2",
                    "status": "final",
                    "code": {"text": "Blood Oxygen (SpO2)"},
                    "valueString": "98%",
                },
                "request": {"method": "PUT", "url": "Observation/obs-2"},
            },
        ],
    }


@pytest.fixture
def sample_jeevandata_brief() -> dict:
    """Fixture returning a Jeevandata AI SOAP brief payload."""
    return {
        "sessionId": "session-xyz-789",
        "patientId": "p-555",
        "patientDemographics": {
            "name": "Priya Patel",
            "age": "28",
            "gender": "Female",
            "blood_group": "B+",
            "weight": "58.5",
            "mobile": "9123456780",
            "email": "priya.patel@example.com",
            "address": "12 Lotus Colony, Pune",
            "pincode": "411001",
        },
        "intakeData": {
            "chiefComplaint": "Severe migraine and photophobia",
            "symptoms": [
                {"name": "Headache", "severity": 8, "duration": "2 days"},
                {"name": "Nausea", "severity": 6, "duration": "1 day"},
            ],
        },
        "soapBrief": {
            "subjective": "Patient reports pulsating unilateral headache worsening with light.",
            "objective": "BP 120/80 mmHg, alert, photophobia noted during kiosk intake.",
            "assessment": "Suspected Acute Migraine Episode without Aura.",
            "plan": "Dark room rest, hydration, consider sumatriptan and analgesics.",
        },
    }


class TestFHIRAdapter:
    """Test suite covering FHIR R4 and Jeevandata intake parsing, ingestion, and export."""

    def test_ingest_valid_fhir_bundle(self, test_db, sample_fhir_bundle):
        result = FHIRAdapter.ingest_bundle(sample_fhir_bundle, db=test_db)
        assert isinstance(result, IngestionResult)
        assert result.success is True
        assert result.patient_id is not None
        assert result.record_id is not None

        # Verify Patient in DB
        patient = test_db.get_patient_by_id(result.patient_id)
        assert patient is not None
        assert patient.first_name == "Rahul"
        assert patient.last_name == "Sharma"
        assert patient.mobile == "9876543210"
        assert patient.gender == "Male"

        # Verify Medical Record in DB
        records = test_db.get_patient_medical_history(result.patient_id)
        assert len(records) >= 1
        rec = records[0]
        # (id, patient_id, patient_name, doctor_name, diagnosis, treatment, notes, visit_date)
        assert "Acute fever" in rec[4]
        assert "Body Temperature: 102 F" in rec[6]
        assert "SpO2" in rec[6]

    def test_ingest_jeevandata_soap_brief(self, test_db, sample_jeevandata_brief):
        result = FHIRAdapter.ingest_jeevandata_brief(sample_jeevandata_brief, db=test_db)
        assert result.success is True
        assert result.patient_id is not None
        assert result.record_id is not None

        patient = test_db.get_patient_by_id(result.patient_id)
        assert patient is not None
        assert patient.first_name == "Priya"
        assert patient.last_name == "Patel"
        assert patient.mobile == "9123456780"

        records = test_db.get_patient_medical_history(result.patient_id)
        assert len(records) >= 1
        rec = records[0]
        assert "Migraine" in rec[4]
        assert "sumatriptan" in rec[5]
        assert "Subjective:" in rec[6]

    def test_ingest_as_json_string(self, test_db, sample_fhir_bundle):
        json_str = json.dumps(sample_fhir_bundle)
        result = FHIRAdapter.ingest_bundle(json_str, db=test_db)
        assert result.success is True
        assert result.patient_id is not None

    def test_deduplication_by_mobile_number(self, test_db, sample_fhir_bundle):
        # Ingest first time
        res1 = FHIRAdapter.ingest_bundle(sample_fhir_bundle, db=test_db)
        assert res1.success is True

        # Ingest second time with same mobile number
        res2 = FHIRAdapter.ingest_bundle(sample_fhir_bundle, db=test_db)
        assert res2.success is True

        # Should map to the same patient ID
        assert res1.patient_id == res2.patient_id
        # But create a new medical record
        assert res1.record_id != res2.record_id

        # Patient should only exist once
        test_db.cur.execute("SELECT COUNT(*) FROM patients WHERE mobile = '9876543210'")
        count = test_db.cur.fetchone()[0]
        assert count == 1

        # Medical records count should be 2
        history = test_db.get_patient_medical_history(res1.patient_id)
        assert len(history) == 2

    def test_invalid_payload_handling(self, test_db):
        # Missing bundle
        res = FHIRAdapter.ingest_bundle({"resourceType": "Observation"}, db=test_db)
        assert res.success is False
        assert "not a FHIR Bundle" in res.message

        # Empty bundle entries
        res = FHIRAdapter.ingest_bundle({"resourceType": "Bundle", "entry": []}, db=test_db)
        assert res.success is False
        assert "no entries" in res.message

        # Bundle missing patient resource
        no_patient_bundle = {
            "resourceType": "Bundle",
            "entry": [{"resource": {"resourceType": "Observation", "id": "1"}}],
        }
        res = FHIRAdapter.ingest_bundle(no_patient_bundle, db=test_db)
        assert res.success is False
        assert "Missing Patient resource" in res.message

        # Malformed JSON string
        res = FHIRAdapter.ingest_bundle("invalid-json{", db=test_db)
        assert res.success is False

    def test_export_patient_to_fhir(self, test_db, sample_fhir_bundle):
        # Ingest to populate data
        res = FHIRAdapter.ingest_bundle(sample_fhir_bundle, db=test_db)
        assert res.success is True
        assert res.patient_id is not None
        patient_id = res.patient_id

        # Export back to FHIR
        exported_bundle = FHIRAdapter.export_patient_to_fhir(patient_id, db=test_db)
        assert exported_bundle["resourceType"] == "Bundle"
        assert exported_bundle["type"] == "transaction"

        entries = exported_bundle["entry"]
        assert len(entries) >= 2  # Patient + Encounter + Obs

        # Verify Patient entry
        patient_entry = entries[0]["resource"]
        assert patient_entry["resourceType"] == "Patient"
        assert patient_entry["name"][0]["family"] == "Sharma"
        assert patient_entry["name"][0]["given"] == ["Rahul"]
        assert patient_entry["telecom"][0]["value"] == "9876543210"

        # Verify Encounter entry
        encounter_entry = entries[1]["resource"]
        assert encounter_entry["resourceType"] == "Encounter"
        assert encounter_entry["subject"]["reference"] == f"Patient/{patient_id}"

    def test_export_nonexistent_patient(self, test_db):
        with pytest.raises(ValueError, match="Patient #99999 not found"):
            FHIRAdapter.export_patient_to_fhir(99999, db=test_db)
